------------------
-- Instructions --
------------------

-- This is a Lua file containing all the text in the game.
-- To translate the text in the game change the strings to their translated versions.
-- Some things to note is that since double quotes are needed to enclose the strings, they need to be escaped
-- if they are needed inside a string, by writing them as \" (see t[99] as an example).
--
-- The comments at the end of each line give some additional information about the text.
-- Text tagged as INES, PRESIDENT_INES, LEE, HOLEEGRAM, COLLECTOR, ANDREA, PAOLO, PEPPE is text that appears as spoken
-- dialogue, and the tag indicates which character is speaking.
-- PEPPE, PAOLO, and ANDREA are the three musicians in the sixties, from left to right.
-- Text tagged as LOOK appears only as the description of an object/hotspot when the cursor is above it.
-- Text tagged as ECHO appears as a dialogue option that is also spoken by the protagonist when selected.
-- Text tagged as NOECHO appears only as a dialogue option but is not spoken.
-- Text tagged as TEXT
--
-- If the language you are translating into does not use spaces between words you will need to break lines manually
-- inside the text that needs to wrap (text spoken by the characters, as well as LOOK and ECHO tags).
-- Line breaks are encoded as \n inside Lua strings. You can test how the text will be displayed with the provided online tester,
-- which can be found at https://sellaroli.com/apps/nem-translation-tool/
--
---------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------

local t = {}

t[1] = "No puedo hacerlo."  -- {TEXT, input.moon}
t[2] = "Eso no funcionará."  -- {TEXT, input.moon}
t[3] = "Nah."  -- {TEXT, input.moon}
t[4] = "Quizás más tarde."  -- {TEXT, input.moon}
t[5] = "Opciones"  -- {TEXT, ui/cursor.moon}
t[6] = "El vacío, el vacío everywhere."  -- {LOOK, rooms/present.moon}
t[7] = "Ventanas"  -- {TEXT, rooms/present.moon}
t[8] = "Al menos ahora tiene una razón para no mirar el volante."  -- {LOOK, rooms/present.moon}
t[9] = "Tío Lee"  -- {TEXT, rooms/present.moon}
t[10] = "Aquí está."  -- {INES, rooms/present.moon}
t[11] = "Espero que esto funcione, y por tu propio bien."  -- {INES, rooms/present.moon}
t[12] = "No soy muy fan de quedarme atrapada en un túnel temporal."  -- {INES, rooms/present.moon}
t[357] = "Tranquila, estaremos devuelta en nuestra línea de tiempo en un santiamén."  -- {LEE, rooms/present.moon}
t[13] = "Debí esperar algo así."  -- {INES, rooms/present.moon}
t[14] = "No viene al caso, es el dispositivo inservible que me paso."  -- {INES, rooms/present.moon}
t[15] = "¿Por qué tío Lee, por qué?"  -- {LOOK, rooms/present.moon}
t[16] = "Navegador temporal"  -- {TEXT, rooms/present.moon}
t[17] = "Parece un teléfono."  -- {INES, rooms/present.moon}
t[18] = "¿Hizo una máquina del tiempo con un teléfono!?"  -- {INES, rooms/present.moon}
t[19] = "A veces están en el marcado rápido."  -- {INES, rooms/present.moon}
t[20] = "Planta"  -- {TEXT, rooms/present.moon}
t[21] = "¿Por qué el tío Lee guardó una planta en la van?"  -- {LOOK, rooms/present.moon}
t[22] = "Hay algo escondido en la maceta!"  -- {INES, rooms/present.moon}
t[23] = "Es un dispositivo de repuesto."  -- {INES, rooms/present.moon}
t[24] = "¿Cómo llego aquí?"  -- {INES, rooms/present.moon}
t[25] = "Encontré el dispositivo en esta maceta."  -- {INES, rooms/present.moon}
t[26] = "No creo ayude si lo vuelvo a guardar."  -- {INES, rooms/present.moon}
t[27] = "Pero siento que voy por buen camino."  -- {INES, rooms/present.moon}
t[62] = "Está mirando ese poster intensamente."  -- {LOOK, rooms/collector.moon}
t[63] = "Me está mirando intensamente."  -- {LOOK, rooms/collector.moon}
t[64] = "Está escuchando la demo intensamente."  -- {LOOK, rooms/collector.moon}
t[65] = "¿?"  -- {TEXT, rooms/collector.moon}
t[66] = "Coleccionista"  -- {TEXT, rooms/collector.moon}
t[67] = "Toma."  -- {INES, rooms/collector.moon}
t[371] = "¿Esto es..."  -- {COLLECTOR, rooms/collector.moon}
t[372] = "...lo que yo creo que es?"  -- {COLLECTOR, rooms/cCCollector.moon}
t[68] = "Sip."  -- {INES, rooms/collector.moon}
t[373] = "¡Parece auténtico!"  -- {COLLECTOR, rooms/collector.moon}
t[374] = "¡No puedo creerlo!"  -- {COLLECTOR, rooms/collector.moon}
t[375] = "Voy a tener que escucharlo ahora mismo para cerciorarme."  -- {COLLECTOR, rooms/collector.moon}
t[376] = "Por favor no toques nada mientras estoy distraída."  -- {COLLECTOR, rooms/collector.moon}
t[69] = "Toma."  -- {INES, rooms/collector.moon}
t[377] = "¿Qué es esto?"  -- {COLLECTOR, rooms/collector.moon}
t[70] = "Es una demo de la banda dueña de esta van."  -- {INES, rooms/collector.moon}
t[71] = "Es la demo que tanto querías."  -- {INES, rooms/collector.moon}
t[378] = "Imposible, el casete se ve nuevo."  -- {COLLECTOR, rooms/collector.moon}
t[379] = "¿Quieres que te crea que es de los sesenta?"  -- {COLLECTOR, rooms/collector.moon}
t[72] = "¡Lo es, te lo juro!"  -- {INES, rooms/collector.moon}
t[380] = "Buena excusa, niña del futuro."  -- {COLLECTOR, rooms/collector.moon}
t[381] = "Toma tu basura."  -- {COLLECTOR, rooms/collector.moon}
t[73] = "Ya lo intenté y no cree que sea auténtica."  -- {INES, rooms/collector.moon}
t[74] = "No se ve lo suficientemente viejo."  -- {INES, rooms/collector.moon}
t[75] = "Sospechoso."  -- {LOOK, rooms/collector.moon}
t[76] = "Uñeta"  -- {TEXT, rooms/collector.moon}
t[77] = "Usaron la uñeta original para hacer el afiche."  -- {INES, rooms/collector.moon}
t[78] = "Algo totalmente normal y cuerdo que hacer."  -- {INES, rooms/collector.moon}
t[79] = "Una pose notable. La composición se enfoca hacia la uñeta."  -- {LOOK, rooms/collector.moon}
t[80] = "Adelantado a su tiempo. Oye, ¿no era diferente antes?"  -- {LOOK, rooms/collector.moon}
t[81] = "Afiche"  -- {TEXT, rooms/collector.moon}
t[82] = "Oye, la uñeta que el guitarrista sostiene no parece plana."  -- {INES, rooms/collector.moon}
t[83] = "Eso es lo que los artistas llamarían «en relieve»."  -- {INES, rooms/collector.moon}
t[84] = "Una grabadora roja de casete de estilo antiguo. Debo tenerla."  -- {LOOK, rooms/collector.moon}
t[85] = "Grabadora de casetes"  -- {TEXT, rooms/collector.moon}
t[382] = "¡No toques eso!"  -- {COLLECTOR, rooms/collector.moon}
t[383] = "Es invaluable."  -- {COLLECTOR, rooms/collector.moon}
t[86] = "Rayos."  -- {INES, rooms/collector.moon}
t[87] = "Je, je."  -- {INES, rooms/collector.moon}
t[384] = "Oh, otra vez tú."  -- {COLLECTOR, rooms/collector.moon}
t[385] = "¡OYE!"  -- {COLLECTOR, rooms/collector.moon}
t[386] = "¡Aléjate de ahí!"  -- {COLLECTOR, rooms/collector.moon}
t[387] = "No te quiero cerca de mi afiche único en su especie."  -- {COLLECTOR, rooms/collector.moon}
t[88] = "Planta"  -- {TEXT, rooms/collector.moon}
t[89] = "¿Esta es la misma planta que el tío Lee guarda en la van?"  -- {LOOK, rooms/collector.moon}
t[90] = "Entonces..."  -- {INES, rooms/collector.moon}
t[91] = "...Encontré el dispositivo funcional que le dí al tío Lee en el jarrón de la planta."  -- {INES, rooms/collector.moon}
t[92] = "El cual supongo que en realidad era el mismo que tengo ahora."  -- {INES, rooms/collector.moon}
t[93] = "Entonces para resolver la inconsistencia debo colocar esto aquí, así mi yo del pasado podrá encontrarlo en el futuro."  -- {INES, rooms/collector.moon}
t[94] = "El cual es en realidad el presente."  -- {INES, rooms/collector.moon}
t[95] = "...caray."  -- {INES, rooms/collector.moon}
t[96] = "El viaje en el tiempo es RE LOCO."  -- {INES, rooms/collector.moon}
t[97] = "Colocaré el dispositivo dentro del jarrón y presionaré el botón desde ahí."  -- {INES, rooms/collector.moon}
t[98] = "Libros"  -- {TEXT, rooms/collector.moon}
t[99] = "Todos son copias del mismo libro: «Una Banda sin Batería»."  -- {LOOK, rooms/collector.moon}
t[100] = "Discos"  -- {TEXT, rooms/collector.moon}
t[101] = "Se ven más nuevos que el resto de cosas aquí."  -- {LOOK, rooms/collector.moon}
t[102] = "LPs"  -- {TEXT, rooms/collector.moon}
t[103] = "Un montón de vinilos. Sí, soy lo bastante mayor para saber qué son esos."  -- {LOOK, rooms/collector.moon}
t[104] = "Estéreo"  -- {TEXT, rooms/collector.moon}
t[105] = "De vanguardia,  o al menos lo habría sido hace unas décadas."  -- {LOOK, rooms/collector.moon}
t[28] = "No puedo alcanzarla, está detrás de este campo de fuerza."  -- {INES, rooms/future.moon}
t[29] = "El único oro en este juego."  -- {LOOK, rooms/future.moon}
t[30] = "Eso parece familiar."  -- {LOOK, rooms/future.moon}
t[31] = "Moneda"  -- {TEXT, rooms/future.moon}
t[32] = "Pensé que no había oro en este juego!"  -- {INES, rooms/future.moon}
t[33] = "Oye, solo está bañado en oro."  -- {INES, rooms/future.moon}
t[34] = "Espero que esto no cause problemas mas adelante."  -- {INES, rooms/future.moon}
t[35] = "Una placa con una descripción de la moneda."  -- {LOOK, rooms/future.moon}
t[36] = "Placa"  -- {TEXT, rooms/future.moon}
t[37] = "Dice que es una reproducción de la primera moneda que ganó el tío Lee."  -- {INES, rooms/future.moon}
t[38] = "Al parecer la original se perdió en mi niñez."  -- {INES, rooms/future.moon}
t[39] = "Je, je."  -- {INES, rooms/future.moon}
t[40] = "¿En qué se ha metido esta vez?"  -- {LOOK, rooms/future.moon}
t[41] = "De alguna forma, me sigue sorprendiendo."  -- {LOOK, rooms/future.moon}
t[42] = "¿Tío Lee?"  -- {TEXT, rooms/future.moon}
t[43] = "HoLeegrama"  -- {TEXT, rooms/future.moon}
t[44] = "¿Tío Lee?"  -- {INES, rooms/future.moon}
t[45] = "No puede oírme detrás del campo de fuerza."  -- {INES, rooms/future.moon}
t[46] = "Una bella escotilla, no se nota por la resolución, pero es muy ornamental."  -- {LOOK, rooms/future.moon}
t[47] = "Apertura"  -- {TEXT, rooms/future.moon}
t[48] = "No puedo hacer eso desde aquí."  -- {INES, rooms/future.moon}
t[49] = "Aquí está una de las cosas que necesitabas."  -- {INES, rooms/future.moon}
t[50] = "Aquí está lo otro que necesitabas."  -- {INES, rooms/future.moon}
t[358] = "¡Delicioso!"  -- {HOLEEGRAM, rooms/future.moon}
t[51] = "...¿qué?"  -- {INES, rooms/future.moon}
t[359] = "No dije nada."  -- {HOLEEGRAM, rooms/future.moon}
t[52] = "No importa, ¿Puedes arreglar esta cosa o no?"  -- {INES, rooms/future.moon}
t[360] = "Trabajando en ello."  -- {HOLEEGRAM, rooms/future.moon}
t[361] = "Bip bup."  -- {HOLEEGRAM, rooms/future.moon}
t[362] = "Bzzzzzzzzzzz."  -- {HOLEEGRAM, rooms/future.moon}
t[363] = "Ahí tienes."  -- {HOLEEGRAM, rooms/future.moon}
t[53] = "¿Por qué lo haría?"  -- {INES, rooms/future.moon}
t[54] = "Están sentados muy quietos, debe ser incómodo."  -- {LOOK, rooms/past.moon}
t[55] = "Músicos de baja fibra moral"  -- {TEXT, rooms/past.moon}
t[56] = "¿Por qué lo haría?"  -- {INES, rooms/past.moon}
t[57] = "¿Es ésta la uñeta que buscas?"  -- {INES, rooms/past.moon}
t[364] = "¡Mi uñeta!"  -- {PEPPE, rooms/past.moon}
t[365] = "¡Mi hermosa uñeta!"  -- {PEPPE, rooms/past.moon}
t[366] = "Te extrañamos mucho, amiguito!"  -- {PAOLO, rooms/past.moon}
t[367] = "No nos asustes así otra vez!"  -- {ANDREA, rooms/past.moon}
t[58] = "¿Me das tu guitarra ahora?"  -- {INES, rooms/past.moon}
t[368] = "Sí, claro, traeré una del almacén."  -- {PEPPE, rooms/past.moon}
t[369] = "Eso duele."  -- {PEPPE, rooms/past.moon}
t[370] = "Esto me da una idea para una portada de álbum."  -- {PAOLO, rooms/past.moon}
t[59] = "Lo encenderé si hablamos algo interesante."  -- {INES, rooms/past.moon}
t[60] = "Esa no se parece a la planta del tío Lee."  -- {LOOK, rooms/past.moon}
t[61] = "Planta sospechosa"  -- {TEXT, rooms/past.moon}
t[106] = "Nunca he visto a nadie guardar guantes aquí."  -- {LOOK, rooms/common.moon}
t[107] = "Guantera"  -- {TEXT, rooms/common.moon}
t[108] = "Está vacío."  -- {INES, rooms/common.moon}
t[109] = "Tomaré el casete."  -- {INES, rooms/common.moon}
t[110] = "Perfectamente maduro."  -- {INES, rooms/common.moon}
t[111] = "Menos mal que nadie usó este compartimento en todos estos años."  -- {INES, rooms/common.moon}
t[112] = "Lo colocaré adentro."  -- {INES, rooms/common.moon}
t[113] = "No es necesario, ya lo envejecí."  -- {INES, rooms/common.moon}
t[114] = "Navegador temporal"  -- {TEXT, inventory.moon}
t[115] = "Es el navegador temporal que comenzó este lío."  -- {LOOK, inventory.moon}
t[116] = "Moneda"  -- {TEXT, inventory.moon}
t[117] = "Me pregunto si hay chocolate adentro."  -- {LOOK, inventory.moon}
t[118] = "Dispositivo repara-realidad patentado"  -- {TEXT, inventory.moon}
t[119] = "¿QUIÉN lo colocó en ese jarrón, y POR QUÉ?"  -- {LOOK, inventory.moon}
t[120] = "Dispositivo repara-realidad patentado (ojalá funcionando)"  -- {TEXT, inventory.moon}
t[121] = "Arreglado y listo."  -- {LOOK, inventory.moon}
t[122] = "Por supuesto no podía ser así de fácil."  -- {LOOK, inventory.moon}
t[123] = "Veamos si esta cosa realmente funciona."  -- {INES, inventory.moon}
t[633] = "¡Detente!"  -- {PRESIDENT_INES, inventory.moon}
t[124] = "... ¿que!?"  -- {INES, inventory.moon}
t[125] = "¿Quién eres?"  -- {INES, inventory.moon}
t[634] = "Correcto."  -- {PRESIDENT_INES, inventory.moon}
t[635] = "No te asustes. Soy tú, pero del futuro."  -- {PRESIDENT_INES, inventory.moon}
t[388] = "Hola Ines!"  -- {HOLEEGRAM, inventory.moon}
t[389] = "¡Guau!"  -- {ANDREA, inventory.moon}
t[126] = "Caraj-"  -- {INES, inventory.moon}
t[636] = "No es hora de perder el tiempo."  -- {PRESIDENT_INES, inventory.moon}
t[637] = "Tengo cosas importantes que hacer."  -- {PRESIDENT_INES, inventory.moon}
t[638] = "Yo soy LA PRESIDENTA."  -- {PRESIDENT_INES, inventory.moon}
t[127] = "Que geni--"  -- {INES, inventory.moon}
t[639] = "¿Qué es lo que dije?"  -- {PRESIDENT_INES, inventory.moon}
t[128] = "Perdone señora."  -- {INES, inventory.moon}
t[640] = "Vine a detenerte para que no destruyas el continuo espacio-tiempo."  -- {PRESIDENT_INES, inventory.moon}
t[641] = "Si presionas ese botón ahora mismo, resultará en un error de inconsistencia temporal."  -- {PRESIDENT_INES, inventory.moon}
t[642] = "Vas a tener que solucionar la inconsistencia antes de utilizar el dispositivo."  -- {PRESIDENT_INES, inventory.moon}
t[129] = "¿Puedes decirme cómo?"  -- {INES, inventory.moon}
t[643] = "Me gustaría pero cuando estaba (literalmente) en tus zapatos, la Inés del futuro no me lo dijo."  -- {PRESIDENT_INES, inventory.moon}
t[644] = "Así que, si te digo, se creara otra inconsistencia."  -- {PRESIDENT_INES, inventory.moon}
t[130] = "Rayos."  -- {INES, inventory.moon}
t[645] = "Eso mismo dije."  -- {PRESIDENT_INES, inventory.moon}
t[646] = "Te lo encargo."  -- {PRESIDENT_INES, inventory.moon}
t[647] = "El deber me llama."  -- {PRESIDENT_INES, inventory.moon}
t[390] = "¡Chau Inés!"  -- {HOLEEGRAM, inventory.moon}
t[131] = "Repara-realidad patentado (averiado)"  -- {TEXT, inventory.moon}
t[132] = "Baratijas del tío Lee."  -- {LOOK, inventory.moon}
t[133] = "Uñeta de guitarra"  -- {TEXT, inventory.moon}
t[134] = "¿Es eso sangre?"  -- {LOOK, inventory.moon}
t[135] = "Grabadora de casetes"  -- {TEXT, inventory.moon}
t[136] = "Tiene un casete dentro. Conveniente."  -- {LOOK, inventory.moon}
t[137] = "Guitarra eléctrica"  -- {TEXT, inventory.moon}
t[138] = "Casete"  -- {TEXT, inventory.moon}
t[139] = "Me pregunto si esto es legal."  -- {LOOK, inventory.moon}
t[140] = "Casete viejo"  -- {TEXT, inventory.moon}
t[141] = "Me pregunto si mejoró al envejecerse."  -- {LOOK, inventory.moon}
t[142] = "Pastilla magnética"  -- {TEXT, inventory.moon}
t[143] = "Se sintió bien obtener esto."  -- {LOOK, inventory.moon}
t[144] = "Tío Lee, ¿seguro que no quieres que conduzca?"  -- {INES, dialogues/lee.moon}
t[391] = "¡Está bien, Inés querida! Disfruta el viaje."  -- {LEE, dialogues/lee.moon}
t[145] = "Lo disfrutaría más si miraras el camino."  -- {INES, dialogues/lee.moon}
t[392] = "Lo ví muchas veces, no tiene nada de especial."  -- {LEE, dialogues/lee.moon}
t[146] = "¡Ay!, ¿al menos sabes si es la ruta correcta?"  -- {INES, dialogues/lee.moon}
t[393] = "¡Obvio, podría conducir al Lago Fenfef a ojos cerrados!"  -- {LEE, dialogues/lee.moon}
t[147] = "No sería tan diferente de lo que haces ahora."  -- {INES, dialogues/lee.moon}
t[148] = "...llevamos mucho tiempo en este tunel, ¿No?"  -- {INES, dialogues/lee.moon}
t[394] = "Estos túneles parecen INTERMINABLES!"  -- {LEE, dialogues/lee.moon}
t[149] = "Tío Lee."  -- {INES, dialogues/lee.moon}
t[395] = "Oh dios."  -- {LEE, dialogues/lee.moon}
t[150] = "TÍO LEE."  -- {INES, dialogues/lee.moon}
t[396] = "Debo haberme sentado en el navegador temporal."  -- {LEE, dialogues/lee.moon}
t[397] = "Por eso no podía encontrarlo en ningúna parte."  -- {LEE, dialogues/lee.moon}
t[151] = "¿¡NAVEGADOR TEMPORAL!?"  -- {INES, dialogues/lee.moon}
t[398] = "Nada de qué preocuparse."  -- {LEE, dialogues/lee.moon}
t[399] = "Para estas ocasiones llevo mi Repararealidad patentado."  -- {LEE, dialogues/lee.moon}
t[400] = "Oh. Oh, creo que se rompió."  -- {LEE, dialogues/lee.moon}
t[152] = "Maravilloso."  -- {INES, dialogues/lee.moon}
t[401] = "Debería haber uno de repuesto por aquí cerca."  -- {LEE, dialogues/lee.moon}
t[402] = "Quédate con éste también."  -- {LEE, dialogues/lee.moon}
t[153] = "¿Tío Lee?"  -- {INES, dialogues/lee.moon}
t[403] = "¿Sí, querida?"  -- {LEE, dialogues/lee.moon}
t[154] = "¿Dónde debería buscar el dispositivo?"  -- {ECHO, dialogues/lee.moon}
t[155] = "¿Qué es este navegador temporal?"  -- {ECHO, dialogues/lee.moon}
t[156] = "Esta van se ve más grande de lo que debería."  -- {ECHO, dialogues/lee.moon}
t[157] = "OK, adiós."  -- {ECHO, dialogues/lee.moon}
t[404] = "¡Adiós!"  -- {LEE, dialogues/lee.moon}
t[405] = "No lo sé."  -- {LEE, dialogues/lee.moon}
t[406] = "¿Donde lo habrías puesto TÚ?"  -- {LEE, dialogues/lee.moon}
t[158] = "¿¡YO!?"  -- {INES, dialogues/lee.moon}
t[159] = "¡Tú lo guardaste!"  -- {INES, dialogues/lee.moon}
t[407] = "Supuestamente."  -- {LEE, dialogues/lee.moon}
t[408] = "¡Es mi más reciente (y más genial) invento!"  -- {LEE, dialogues/lee.moon}
t[409] = "Está recién salido del horno, ni he registrado el nombre aún"  -- {LEE, dialogues/lee.moon}
t[160] = "¿Qué hace?"  -- {ECHO, dialogues/lee.moon}
t[161] = "Recuérdame qué hace."  -- {ECHO, dialogues/lee.moon}
t[162] = "¿Por qué inventarías tal cosa?"  -- {ECHO, dialogues/lee.moon}
t[163] = "Recuérdame porqué lo creaste"  -- {ECHO, dialogues/lee.moon}
t[164] = "No importa."  -- {ECHO, dialogues/lee.moon}
t[410] = "¡Qué pregunta tan absurda!"  -- {LEE, dialogues/lee.moon}
t[411] = "Es un dispositivo para navegar a través del tiempo."  -- {LEE, dialogues/lee.moon}
t[412] = "Está justo ahí en el nombre."  -- {LEE, dialogues/lee.moon}
t[165] = "¿No es peligroso?"  -- {INES, dialogues/lee.moon}
t[413] = "No si sabes lo que haces."  -- {LEE, dialogues/lee.moon}
t[166] = "¿Y TÚ sabes lo que haces?"  -- {INES, dialogues/lee.moon}
t[414] = "Más o menos."  -- {LEE, dialogues/lee.moon}
t[415] = "Es un dispositivo para navegar a través del tiempo."  -- {LEE, dialogues/lee.moon}
t[416] = "Bueno, el otro cocinaba y me dí cuenta de que me quedé sin tenedores."  -- {LEE, dialogues/lee.moon}
t[167] = "¡No deberías usar cubiertos desechables, tío Lee!"  -- {INES, dialogues/lee.moon}
t[168] = "¡Es malo para el medio ambiente!"  -- {INES, dialogues/lee.moon}
t[417] = "Por supuesto, todos mis tenedores son reutilizables."  -- {LEE, dialogues/lee.moon}
t[169] = "¿Y se te acabaron?"  -- {INES, dialogues/lee.moon}
t[418] = "Sí."  -- {LEE, dialogues/lee.moon}
t[419] = "Como decía, recordé que me quedaban algunos el día anterior."  -- {LEE, dialogues/lee.moon}
t[420] = "Así que decidí crear una máquina del tiempo para regresar y tomarlos."  -- {LEE, dialogues/lee.moon}
t[421] = "Ahora que lo pienso, tal vez por eso se me acabaron en primer lugar."  -- {LEE, dialogues/lee.moon}
t[422] = "Para volver en el tiempo y robar algunos tenedores."  -- {LEE, dialogues/lee.moon}
t[423] = "De mí mismo."  -- {LEE, dialogues/lee.moon}
t[170] = "Correcto."  -- {INES, dialogues/lee.moon}
t[424] = "Trataron de dibujarla con proporciones realistas pero eso no funcionaba bien."  -- {LEE, dialogues/lee.moon}
t[171] = "...¿qué?"  -- {INES, dialogues/lee.moon}
t[425] = "Es decir, fue hecha especialmente para una banda de los sesenta."  -- {LEE, dialogues/lee.moon}
t[172] = "¿De dónde la sacaste?"  -- {INES, dialogues/lee.moon}
t[426] = "La obtuve de una coleccionista."  -- {LEE, dialogues/lee.moon}
t[173] = "¡Eso debe haber sido muy caro!"  -- {INES, dialogues/lee.moon}
t[427] = "¿Caro?"  -- {LEE, dialogues/lee.moon}
t[174] = "Tío Lee, ¿la robaste?"  -- {INES, dialogues/lee.moon}
t[428] = "La gané, limpio y justo."  -- {LEE, dialogues/lee.moon}
t[429] = "No es mi culpa si ella no sabía cómo jugar a la brisca."  -- {LEE, dialogues/lee.moon}
t[430] = "Es un modelo personalizado hecho para una banda en los sesenta."  -- {LEE, dialogues/lee.moon}
t[431] = "La obtuve de una coleccionista."  -- {LEE, dialogues/lee.moon}
t[175] = "Hola."  -- {INES, dialogues/wilson.moon}
t[176] = "Nada digno de registrar."  -- {INES, dialogues/wilson.moon}
t[177] = "Estos tipos son aburridos."  -- {INES, dialogues/wilson.moon}
t[178] = "Ya está."  -- {INES, dialogues/wilson.moon}
t[179] = "Me preguntó si esta cinta valdrá algo algún día."  -- {INES, dialogues/wilson.moon}
t[432] = "Chicos, ¡No creerán lo que estoy viendo!"  -- {PAOLO, dialogues/wilson.moon}
t[433] = "¡Una chica gruñona con cabello VERDE!"  -- {PAOLO, dialogues/wilson.moon}
t[434] = "Se ve ENOJADA."  -- {PAOLO, dialogues/wilson.moon}
t[435] = "Todos podemos verla, bobo."  -- {ANDREA, dialogues/wilson.moon}
t[436] = "Debe ser otra viajera temporal."  -- {PEPPE, dialogues/wilson.moon}
t[437] = "¡Vaya!"  -- {PAOLO, dialogues/wilson.moon}
t[180] = "Entonces son una banda, ¿cierto?"  -- {ECHO, dialogues/wilson.moon}
t[438] = "¿Qué nos delató?"  -- {ANDREA, dialogues/wilson.moon}
t[181] = "Las guitarras, obvio."  -- {ECHO, dialogues/wilson.moon}
t[439] = "¿Por qué «la batería» no está entre las opciones?"  -- {PAOLO, dialogues/wilson.moon}
t[182] = "Los peinados descuida«os pero elaborados y la actitud rebelde."  -- {ECHO, dialogues/wilson.moon}
t[440] = "Mira quién habla."  -- {PEPPE, dialogues/wilson.moon}
t[183] = "Instinto."  -- {ECHO, dialogues/wilson.moon}
t[441] = "Sí, seguro."  -- {ANDREA, dialogues/wilson.moon}
t[184] = "Por el símbolo de al fondo."  -- {ECHO, dialogues/wilson.moon}
t[442] = "Técnicamente eso no significa que seamos una banda."  -- {PEPPE, dialogues/wilson.moon}
t[185] = "¿No lo son?"  -- {INES, dialogues/wilson.moon}
t[443] = "...sí."  -- {PEPPE, dialogues/wilson.moon}
t[186] = "Sobre su banda..."  -- {ECHO, dialogues/wilson.moon}
t[187] = "Estoy buscando algo."  -- {ECHO, dialogues/wilson.moon}
t[188] = "Eso es todo."  -- {ECHO, dialogues/wilson.moon}
t[444] = "Adiós."  -- {ANDREA, dialogues/wilson.moon}
t[445] = "No confío en ti, visión de cabello verde."  -- {PAOLO, dialogues/wilson.moon}
t[446] = "Siéntete libre de quedarte y explorar nuestra humilde van."  -- {PEPPE, dialogues/wilson.moon}
t[189] = "¿Ensayan en esta van?"  -- {ECHO, dialogues/wilson.moon}
t[447] = "Sí, la hicimos a medida."  -- {PAOLO, dialogues/wilson.moon}
t[448] = "También dormimos aquí."  -- {ANDREA, dialogues/wilson.moon}
t[190] = "Ingenioso."  -- {INES, dialogues/wilson.moon}
t[449] = "Tuvimos que vender nuestras casas para pagarla."  -- {PEPPE, dialogues/wilson.moon}
t[450] = "Y mi batería."  -- {PAOLO, dialogues/wilson.moon}
t[451] = "Pero no nos arrepentimos."  -- {ANDREA, dialogues/wilson.moon}
t[452] = "Es la mejor decisión de nuestras vidas."  -- {PEPPE, dialogues/wilson.moon}
t[191] = "¿No te falta una batería?"  -- {ECHO, dialogues/wilson.moon}
t[453] = "Sí."  -- {PAOLO, dialogues/wilson.moon}
t[192] = "...¿no es eso un problema?"  -- {INES, dialogues/wilson.moon}
t[454] = "No."  -- {PAOLO, dialogues/wilson.moon}
t[193] = "¿Están trabajando en alguna canción?"  -- {ECHO, dialogues/wilson.moon}
t[455] = "De hecho, sí."  -- {PEPPE, dialogues/wilson.moon}
t[456] = "La mejor canción de nuestras vidas."  -- {ANDREA, dialogues/wilson.moon}
t[457] = "La tocaremos para ti."  -- {PAOLO, dialogues/wilson.moon}
t[194] = "Debería grabar esto."  -- {INES, dialogues/wilson.moon}
t[195] = "No es necesario..."  -- {INES, dialogues/wilson.moon}
t[196] = "Fue un sufrimiento grato."  -- {INES, dialogues/wilson.moon}
t[458] = "Vaya, eso sería un nombre genial para un álbum."  -- {PAOLO, dialogues/wilson.moon}
t[197] = "Suficiente sobre ustedes."  -- {ECHO, dialogues/wilson.moon}
t[459] = "Se nos acaba de terminar."  -- {PAOLO, dialogues/wilson.moon}
t[460] = "Y antes de que preguntes..."  -- {ANDREA, dialogues/wilson.moon}
t[461] = "...la de atrás es de uso privado."  -- {PEPPE, dialogues/wilson.moon}
t[198] = "¿¡Que!?"  -- {INES, dialogues/wilson.moon}
t[199] = "No quise decir eso."  -- {INES, dialogues/wilson.moon}
t[200] = "¿Por qué asumirías eso?"  -- {INES, dialogues/wilson.moon}
t[462] = "Eso es lo que el tipo con bigote normalmente quiere."  -- {ANDREA, dialogues/wilson.moon}
t[463] = "Tipo raro."  -- {PAOLO, dialogues/wilson.moon}
t[201] = "...por supuesto."  -- {INES, dialogues/wilson.moon}
t[202] = "No tendrán algo de oro escondido en algún lado, ¿verdad?"  -- {ECHO, dialogues/wilson.moon}
t[464] = "No eres la primera en preguntar hoy."  -- {PAOLO, dialogues/wilson.moon}
t[465] = "Yo fui el primero."  -- {PEPPE, dialogues/wilson.moon}
t[466] = "Yo casi soy el segundo."  -- {ANDREA, dialogues/wilson.moon}
t[467] = "De todas maneras, no hay oro en este juego."  -- {PAOLO, dialogues/wilson.moon}
t[203] = "Rayos."  -- {INES, dialogues/wilson.moon}
t[204] = "Imanes. Necesito imanes."  -- {ECHO, dialogues/wilson.moon}
t[205] = "¿Tienen algunos?"  -- {INES, dialogues/wilson.moon}
t[468] = "No lo creo."  -- {PEPPE, dialogues/wilson.moon}
t[469] = "Improbable."  -- {ANDREA, dialogues/wilson.moon}
t[470] = "Diría que bastante improbable."  -- {PAOLO, dialogues/wilson.moon}
t[206] = "Rayos."  -- {INES, dialogues/wilson.moon}
t[207] = "¿Están TOTALMENTE seguros de que no tienen imanes?"  -- {ECHO, dialogues/wilson.moon}
t[471] = "Muy seguros."  -- {ANDREA, dialogues/wilson.moon}
t[472] = "No tenemos ninguna razón para mentirte."  -- {PEPPE, dialogues/wilson.moon}
t[473] = "Habla por ti mismo."  -- {PAOLO, dialogues/wilson.moon}
t[208] = "Me han dicho que las guitarras tienen imanes."  -- {INES, dialogues/wilson.moon}
t[474] = "¡¿Las guitarras tienen imanes?!"  -- {PAOLO, dialogues/wilson.moon}
t[475] = "¡Guau!"  -- {ANDREA, dialogues/wilson.moon}
t[476] = "¡Es tan genial!"  -- {PEPPE, dialogues/wilson.moon}
t[477] = "Entonces, supongo que tenemos imanes."  -- {PEPPE, dialogues/wilson.moon}
t[209] = "¿Me prestan una de sus guitarras?"  -- {ECHO, dialogues/wilson.moon}
t[478] = "Claro, por qué n--"  -- {PAOLO, dialogues/wilson.moon}
t[479] = "¡Por supuesto que no!"  -- {ANDREA, dialogues/wilson.moon}
t[480] = "Las necesitamos."  -- {PEPPE, dialogues/wilson.moon}
t[481] = "Somos una banda y todo eso."  -- {ANDREA, dialogues/wilson.moon}
t[210] = "¿No tienen de repuesto?"  -- {INES, dialogues/wilson.moon}
t[482] = "Bien, ahora que lo pienso..."  -- {PEPPE, dialogues/wilson.moon}
t[483] = "...tenemos muchas en el almacén."  -- {ANDREA, dialogues/wilson.moon}
t[211] = "Entonces, ¿puedo llevarme una?"  -- {INES, dialogues/wilson.moon}
t[484] = "No."  -- {PEPPE, dialogues/wilson.moon}
t[212] = "¿Hay algo que pueda hacer para persuadirte de que me des una guitarra?"  -- {ECHO, dialogues/wilson.moon}
t[485] = "Nop."  -- {PEPPE, dialogues/wilson.moon}
t[486] = "Ni en sueños."  -- {ANDREA, dialogues/wilson.moon}
t[487] = "Chicos, ¿qué tal..."  -- {PAOLO, dialogues/wilson.moon}
t[488] = "...LA UÑETA?"  -- {PAOLO, dialogues/wilson.moon}
t[489] = "Correcto."  -- {PEPPE, dialogues/wilson.moon}
t[490] = "LA UÑETA."  -- {PEPPE, dialogues/wilson.moon}
t[213] = "¿La uñeta?"  -- {INES, dialogues/wilson.moon}
t[491] = "Solía tener esta uñeta hace un tiempo."  -- {PEPPE, dialogues/wilson.moon}
t[492] = "Era una real y fiel uñeta."  -- {PEPPE, dialogues/wilson.moon}
t[493] = "Siempre escuchaba, sin juzgar."  -- {PEPPE, dialogues/wilson.moon}
t[494] = "Siempre se reía de todas mis bromas."  -- {PAOLO, dialogues/wilson.moon}
t[495] = "Básicamente era el cuarto miembro de la banda."  -- {ANDREA, dialogues/wilson.moon}
t[496] = "Pero la perdimos un día, mientras practicámos."  -- {PAOLO, dialogues/wilson.moon}
t[497] = "Un dia de lo más infame."  -- {PEPPE, dialogues/wilson.moon}
t[498] = "Que descanse en paz."  -- {ANDREA, dialogues/wilson.moon}
t[214] = "... Ya veo."  -- {INES, dialogues/wilson.moon}
t[215] = "¿Me darían una guitarra si encontrara su uñeta?"  -- {ECHO, dialogues/wilson.moon}
t[499] = "Encuentra mi uñeta perdida y tenemos un trato."  -- {PEPPE, dialogues/wilson.moon}
t[216] = "No importa."  -- {ECHO, dialogues/wilson.moon}
t[500] = "¡Claro!"  -- {PEPPE, dialogues/wilson.moon}
t[501] = "¡Es mucho mas valiosa que cualquier cosa o persona en esta van!"  -- {PEPPE, dialogues/wilson.moon}
t[502] = "¡Oye!"  -- {ANDREA, dialogues/wilson.moon}
t[503] = "No, él tiene razón."  -- {PAOLO, dialogues/wilson.moon}
t[217] = "¿Alguna idea de dónde podría estar?"  -- {INES, dialogues/wilson.moon}
t[504] = "En Algún lugar de Woodstock, creo."  -- {PEPPE, dialogues/wilson.moon}
t[218] = "Claro."  -- {INES, dialogues/wilson.moon}
t[219] = "¿Coleccionas chaquetas de cuero?"  -- {ECHO, dialogues/collector.moon}
t[220] = "¿Coleccionas barómetros de oro?"  -- {ECHO, dialogues/collector.moon}
t[221] = "¿Coleccionas instrumentos de tortura medievales?"  -- {ECHO, dialogues/collector.moon}
t[222] = "¿Coleccionas vegetales de formas extrañas?"  -- {ECHO, dialogues/collector.moon}
t[223] = "¿Coleccionas poesía de agobio adolescente?"  -- {ECHO, dialogues/collector.moon}
t[224] = "¿Coleccionas miniaturas de mariscos?"  -- {ECHO, dialogues/collector.moon}
t[225] = "¿Coleccionas series de televisión de principios de los 2000?"  -- {ECHO, dialogues/collector.moon}
t[226] = "¿Coleccionas revistas pulp de los cincuenta?"  -- {ECHO, dialogues/collector.moon}
t[227] = "¿Coleccionas mis fotos de anuario escolar?"  -- {ECHO, dialogues/collector.moon}
t[228] = "Fiuuu."  -- {INES, dialogues/collector.moon}
t[229] = "¿Coleccionas calendarios deportivos?"  -- {ECHO, dialogues/collector.moon}
t[230] = "¿Coleccionas bolsas de papas fritas premiadas?"  -- {ECHO, dialogues/collector.moon}
t[231] = "¿Coleccionas llaveros indecentes?"  -- {ECHO, dialogues/collector.moon}
t[232] = "¿Coleccionas llaveros decentes?"  -- {ECHO, dialogues/collector.moon}
t[233] = "¿Coleccionas temas musicales exageradamente exagerados?"  -- {ECHO, dialogues/collector.moon}
t[234] = "¿Coleccionas espadas no-intactas?"  -- {ECHO, dialogues/collector.moon}
t[235] = "¿Coleccionas coleccionistas?"  -- {ECHO, dialogues/collector.moon}
t[236] = "Hola."  -- {INES, dialogues/collector.moon}
t[505] = "Sigues aquí."  -- {COLLECTOR, dialogues/collector.moon}
t[506] = "¡¿QUIÉN ERES?!"  -- {COLLECTOR, dialogues/collector.moon}
t[237] = "...¿viajera en el tiempo, supongo?"  -- {INES, dialogues/collector.moon}
t[507] = "Oh no. ¿Tienes alguna relación con ese tipo raro con el bigote grande?"  -- {COLLECTOR, dialogues/collector.moon}
t[238] = "Oye, solo yo puedo decirle \"raro al tío Lee\"."  -- {INES, dialogues/collector.moon}
t[508] = "Como sea."  -- {COLLECTOR, dialogues/collector.moon}
t[509] = "Vete."  -- {COLLECTOR, dialogues/collector.moon}
t[510] = "AHORA."  -- {COLLECTOR, dialogues/collector.moon}
t[511] = "O al menos no toques nada."  -- {COLLECTOR, dialogues/collector.moon}
t[239] = "La van se ve diferente."  -- {ECHO, dialogues/collector.moon}
t[240] = "¿Qué es toda esta basura?"  -- {INES, dialogues/collector.moon}
t[512] = "¿Basura?"  -- {COLLECTOR, dialogues/collector.moon}
t[513] = "¡¿Basura?!"  -- {COLLECTOR, dialogues/collector.moon}
t[514] = "¡Esta es una colección de grandísimo valor!"  -- {COLLECTOR, dialogues/collector.moon}
t[515] = "No lo entenderías."  -- {COLLECTOR, dialogues/collector.moon}
t[241] = "¿Eres una coleccionista?"  -- {INES, dialogues/collector.moon}
t[516] = "Soy laaa coleccionista."  -- {COLLECTOR, dialogues/collector.moon}
t[242] = "¿Qué tipo de cosas coleccionas?"  -- {ECHO, dialogues/collector.moon}
t[517] = "No llames cosas a estos artefactos invaluables."  -- {COLLECTOR, dialogues/collector.moon}
t[518] = "Me especializo en objetos que hayan pertenecido o tengan relación a LA BANDA."  -- {COLLECTOR, dialogues/collector.moon}
t[519] = "Tengo afiches, álbumes de estudio, discos de vinilo y remasterizados (que hice yo misma...)"  -- {COLLECTOR, dialogues/collector.moon}
t[520] = "...incluso estas mismas paredes eran propiedad de LA BANDA."  -- {COLLECTOR, dialogues/collector.moon}
t[243] = "¿Te refieres a la van?"  -- {INES, dialogues/collector.moon}
t[521] = "Es la mejor colección de la historia."  -- {COLLECTOR, dialogues/collector.moon}
t[522] = "...o sería, si sólo..."  -- {COLLECTOR, dialogues/collector.moon}
t[244] = "Bien, me iré."  -- {ECHO, dialogues/collector.moon}
t[523] = "Excelente."  -- {COLLECTOR, dialogues/collector.moon}
t[245] = "¿Tienes la uñeta perdida de la banda?"  -- {ECHO, dialogues/collector.moon}
t[524] = "¿Cuál de todas?"  -- {COLLECTOR, dialogues/collector.moon}
t[525] = "¿Tienes idea de cuántas uñetas pierde una banda a lo largo de su carrera?"  -- {COLLECTOR, dialogues/collector.moon}
t[526] = "¡Tengo cientos!"  -- {COLLECTOR, dialogues/collector.moon}
t[246] = "¿Pero... la más importante?"  -- {INES, dialogues/collector.moon}
t[527] = "¡¡¡Todas son imporantes!!!"  -- {COLLECTOR, dialogues/collector.moon}
t[528] = "¡Pertenecían a LA BANDA!"  -- {COLLECTOR, dialogues/collector.moon}
t[247] = "...caray."  -- {INES, dialogues/collector.moon}
t[248] = "¿No le falta algo a tu colección?"  -- {ECHO, dialogues/collector.moon}
t[529] = "Cuenta la leyenda que LA BANDA escribió una canción magnífica."  -- {COLLECTOR, dialogues/collector.moon}
t[530] = "Una canción tan celestial que los pájaros que la escuchaban también la cantaban."  -- {COLLECTOR, dialogues/collector.moon}
t[531] = "Desgraciadamante, la canción se perdió."  -- {COLLECTOR, dialogues/collector.moon}
t[532] = "Sin embargo, hay rumores de que se ha hecho una grabación."  -- {COLLECTOR, dialogues/collector.moon}
t[533] = "¡¡¡Un demo!!!"  -- {COLLECTOR, dialogues/collector.moon}
t[534] = "...me encantaría tenerlo."  -- {COLLECTOR, dialogues/collector.moon}
t[249] = "Ya veo."  -- {INES, dialogues/collector.moon}
t[250] = "¿Coleccionas oro?"  -- {ECHO, dialogues/collector.moon}
t[535] = "No hay oro en este juego."  -- {COLLECTOR, dialogues/collector.moon}
t[251] = "Rayos."  -- {INES, dialogues/collector.moon}
t[252] = "¿Coleccionas imanes?"  -- {ECHO, dialogues/collector.moon}
t[536] = "¿Qué clase de rarito colecciona imanes?"  -- {COLLECTOR, dialogues/collector.moon}
t[253] = "...el tío Lee."  -- {INES, dialogues/collector.moon}
t[254] = "¿Coleccionas algo que tenga imanes DENTRO?"  -- {INES, dialogues/collector.moon}
t[537] = "Las guitarras, supongo."  -- {COLLECTOR, dialogues/collector.moon}
t[255] = "¡¿Las guitarras tienen imanes?!"  -- {INES, dialogues/collector.moon}
t[538] = "Claro que sí."  -- {COLLECTOR, dialogues/collector.moon}
t[256] = "¡Genial!"  -- {INES, dialogues/collector.moon}
t[257] = "...no veo ninguna guitarra."  -- {INES, dialogues/collector.moon}
t[539] = "Están en el depósito."  -- {COLLECTOR, dialogues/collector.moon}
t[540] = "Es una colección rotativa."  -- {COLLECTOR, dialogues/collector.moon}
t[258] = "Rayos."  -- {INES, dialogues/collector.moon}
t[541] = "Te dije que las guitarras tienen imanes."  -- {COLLECTOR, dialogues/collector.moon}
t[542] = "Pero no tengo ninguna aquí."  -- {COLLECTOR, dialogues/collector.moon}
t[543] = "No."  -- {COLLECTOR, dialogues/collector.moon}
t[259] = "Aburriiidooo."  -- {ECHO, dialogues/collector.moon}
t[260] = "He vuelto."  -- {INES, dialogues/holeegram.moon}
t[544] = "Coloca el dispositivo en la abertura que está aquí debajo para poder analizarlo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[261] = "...¿tío Lee?"  -- {INES, dialogues/holeegram.moon}
t[545] = "...¿tío Lee? Pequeña Inés! No te he visto en años!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[262] = "...¿qué te pasó?"  -- {INES, dialogues/holeegram.moon}
t[546] = "Soy un HOLEEGRAMA!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[263] = "Por supuesto que lo eres."  -- {INES, dialogues/holeegram.moon}
t[264] = "¿Pero qué? ¿Te pasó algo?"  -- {INES, dialogues/holeegram.moon}
t[547] = "Nada, solo quería probar algo nuevo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[548] = "No me habia sentido tan radiante desde que cumplí 105!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[549] = "Pero dejemos de hablar de mí."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[550] = "Imagino que llegaste aquí usando mi maravilloso navegador temporal patentado."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[265] = "No lo llamaría «maravilloso»..."  -- {NOECHO, dialogues/holeegram.moon}
t[266] = "Tienes suerte de que no puedo golpearte."  -- {NOECHO, dialogues/holeegram.moon}
t[267] = "Estoy aquí porque... ¡te sentaste en una máquina del tiempo!"  -- {NOECHO, dialogues/holeegram.moon}
t[268] = "...sí."  -- {INES, dialogues/holeegram.moon}
t[269] = "¿Cuánto tiempo ha pasado?"  -- {ECHO, dialogues/holeegram.moon}
t[551] = "¡Cientos de años!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[270] = "¿Puedes ayudarme a salir de este túnel del tiempo?"  -- {ECHO, dialogues/holeegram.moon}
t[552] = "¿Túnel del tiempo?"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[271] = "Presionaste tu elegante botón, desapareciste y me dejaste abandonada."  -- {INES, dialogues/holeegram.moon}
t[272] = "¿Te suena?"  -- {INES, dialogues/holeegram.moon}
t[553] = "Oh, cielos..."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[554] = "Tendrás que ser más específica."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[555] = "Recuerdo al menos cinco ocasiones en las que eso ocurrió."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[273] = "Genial."  -- {INES, dialogues/holeegram.moon}
t[274] = "La primera, supongo."  -- {INES, dialogues/holeegram.moon}
t[556] = "¡El viaje al Lago Fenfef!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[275] = "Síp."  -- {INES, dialogues/holeegram.moon}
t[557] = "Tendremos que reparar tu dispositivo repara-realidad patentado, ¿verdad?"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[276] = "No lo sé, TÚ dime."  -- {INES, dialogues/holeegram.moon}
t[558] = "Tendremos que reparar tu dispositivo repara-realidad patentado."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[277] = "¿Qué necesitas para repararlo?"  -- {ECHO, dialogues/holeegram.moon}
t[559] = "Necesito un imán y la moneda del museo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[278] = "Entendido."  -- {INES, dialogues/holeegram.moon}
t[279] = "Es irónico que necesitamos reparar un dispositivo repara-realidad."  -- {ECHO, dialogues/holeegram.moon}
t[560] = "Lo sé."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[561] = "Si tan solo no tuviera mi dispositvo reparador del dispositivo de reparación de la realidad patentado."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[280] = "¿Cómo repararías un dispositvo reparador del dispositivo de reparación de la realidad patentado?"  -- {ECHO, dialogues/holeegram.moon}
t[562] = "Fácil, con un dispositivo repara-dispositivo-reparador-dispositivo de repara-realidad patentado."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[563] = "Ese lo tengo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[281] = "Rayos."  -- {INES, dialogues/holeegram.moon}
t[282] = "¿Tienes alguna idea de cómo arreglar la inconsistencia que me impide usar el dispositivo?"  -- {ECHO, dialogues/holeegram.moon}
t[564] = "Claro que sí, ¡me especializo en inconsistencias!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[565] = "Si mal no recuerdo, solo hice uno de estos dispositivos."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[283] = "Pero recuerdo tener dos de ellos al mismo tiempo."  -- {INES, dialogues/holeegram.moon}
t[566] = "Entonces, quizás la inconsistencia tenga algo que ver con eso."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[284] = "...mmm."  -- {INES, dialogues/holeegram.moon}
t[285] = "Bien, nos vemos después."  -- {ECHO, dialogues/holeegram.moon}
t[567] = "¡O antes!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[286] = "¿Qué pasó conmigo en esta línea temporal?"  -- {ECHO, dialogues/holeegram.moon}
t[568] = "¡Eres la Presidenta!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[287] = "¡Genial!"  -- {INES, dialogues/holeegram.moon}
t[288] = "Espera, ¿presidenta de qué?"  -- {INES, dialogues/holeegram.moon}
t[569] = "Sí, eres la Presidenta de Q.U.E."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[289] = "No importa, solo ayúdame a salir de este lío."  -- {INES, dialogues/holeegram.moon}
t[290] = "¿Qué le pasó a tu cuerpo?"  -- {ECHO, dialogues/holeegram.moon}
t[570] = "Bueno..."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[571] = "No estoy seguro."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[572] = "Lo perdí de alguna forma."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[291] = "¿¡Que!?"  -- {INES, dialogues/holeegram.moon}
t[573] = "Nada de qué preocuparse, querida."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[574] = "La Presidenta Inés está en el caso y estoy seguro que lo encontrará en poco tiempo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[575] = "La Inés del futuro está en el caso y estoy seguro que lo encontrará en poco tiempo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[292] = "Cuanto más aprendo de este tiempo, menos quiero saber."  -- {INES, dialogues/holeegram.moon}
t[293] = "¿Qué pasó con la van?"  -- {ECHO, dialogues/holeegram.moon}
t[576] = "Ahora es el «Museo Tío Lee»."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[294] = "¿¡Ahora eres famoso!?"  -- {INES, dialogues/holeegram.moon}
t[577] = "Bueno, no."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[578] = "Yo soy el que hizo el museo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[295] = "Claro que lo hiciste."  -- {INES, dialogues/holeegram.moon}
t[296] = "No importa."  -- {ECHO, dialogues/holeegram.moon}
t[579] = "Necesitará un par de segundos."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[580] = "Es un modelo antiguo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[581] = "¡Los resultados están listos!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[582] = "¡Estamos de suerte!"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[583] = "Es muy fácil."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[584] = "Solo necesitaremos:"  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[585] = "Un potente imán..."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[586] = "...y una moneda de la parte trasera del museo."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[297] = "¿Dónde puedo encontrar un imán?"  -- {ECHO, dialogues/holeegram.moon}
t[298] = "Imagino que hay muchos aquí en el futuro."  -- {INES, dialogues/holeegram.moon}
t[587] = "En realidad... ya no."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[588] = "No desde el accidente."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[299] = "... está bien."  -- {INES, dialogues/holeegram.moon}
t[300] = "En otras líneas temporales sí hay."  -- {INES, dialogues/holeegram.moon}
t[301] = "La moneda parece curiosamente específica."  -- {ECHO, dialogues/holeegram.moon}
t[589] = "Bueno, técnicamente solo necesito algo de oro."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[590] = "Solo quería facilitarte las cosas."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[302] = "¡Pero no puedo alcanzarla desde aquí!"  -- {INES, dialogues/holeegram.moon}
t[303] = "¿No puedo simplemente buscar otra cosita dorada?"  -- {INES, dialogues/holeegram.moon}
t[591] = "No, no hay más oro en este juego."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[592] = "Lo siento."  -- {HOLEEGRAM, dialogues/holeegram.moon}
t[304] = "Rayos."  -- {INES, dialogues/holeegram.moon}
t[305] = "Gracias, lo tengo."  -- {ECHO, dialogues/holeegram.moon}
t[306] = "Los sesenta."  -- {NOECHO, dialogues/navigator.moon}
t[307] = "Los noventa."  -- {NOECHO, dialogues/navigator.moon}
t[308] = "Presente."  -- {NOECHO, dialogues/navigator.moon}
t[309] = "EL FUTURO."  -- {NOECHO, dialogues/navigator.moon}
t[310] = "Quedarse aquí."  -- {NOECHO, dialogues/navigator.moon}
t[316] = "¿Se acabó?"  -- {INES, dialogues/ending.moon}
t[317] = "¿Es este el tiempo correcto?"  -- {INES, dialogues/ending.moon}
t[593] = "¡Inés, querida!"  -- {LEE, dialogues/ending.moon}
t[594] = "¡Lo lograste!"  -- {LEE, dialogues/ending.moon}
t[595] = "¿Por qué tardaste tanto?"  -- {LEE, dialogues/ending.moon}
t[318] = "¿¡CÓMO POR QUÉ TARDÉ TANTO!?"  -- {INES, dialogues/ending.moon}
t[319] = "¡ME DEJASTE TIRADA EN UN TUNEL DEL TIEMPO!"  -- {INES, dialogues/ending.moon}
t[596] = "¿Lo hice?"  -- {LEE, dialogues/ending.moon}
t[320] = "¡Tu estúpido botón solo funcionó en ti!"  -- {INES, dialogues/ending.moon}
t[597] = "Oh sí, lo había olvidado."  -- {LEE, dialogues/ending.moon}
t[598] = "Bueno, parece que llegaste en una pieza."  -- {LEE, dialogues/ending.moon}
t[599] = "Siempre fuiste muy resolutiva."  -- {LEE, dialogues/ending.moon}
t[321] = "*Quejido*"  -- {INES, dialogues/ending.moon}
t[600] = "No cambiaste nada en el pasado, ¿cierto?"  -- {LEE, dialogues/ending.moon}
t[322] = "Emm..."  -- {INES, dialogues/ending.moon}
t[323] = "Define «cambio»."  -- {INES, dialogues/ending.moon}
t[601] = "Oh dios."  -- {LEE, dialogues/ending.moon}
t[602] = "Quizás quieras dar unos pasos adelante."  -- {LEE, dialogues/ending.moon}
t[603] = "¿Qué sucede aquí?"  -- {COLLECTOR, dialogues/ending.moon}
t[324] = "Oh no."  -- {INES, dialogues/ending.moon}
t[604] = "¿¡Dónde está mi colección!?"  -- {COLLECTOR, dialogues/ending.moon}
t[605] = "¡Guau!"  -- {PAOLO, dialogues/ending.moon}
t[606] = "Oh."  -- {COLLECTOR, dialogues/ending.moon}
t[607] = "Dios."  -- {COLLECTOR, dialogues/ending.moon}
t[608] = "Mío."  -- {COLLECTOR, dialogues/ending.moon}
t[609] = "¿Ustedes son...?"  -- {COLLECTOR, dialogues/ending.moon}
t[610] = "Chicos, miren esos ojos!"  -- {ANDREA, dialogues/ending.moon}
t[611] = "Creo que ella es..."  -- {PAOLO, dialogues/ending.moon}
t[612] = "... ¡Una fan!"  -- {PAOLO, dialogues/ending.moon}
t[613] = "¿Notaron qué todos nuestros fans son un poco gruñones?"  -- {PEPPE, dialogues/ending.moon}
t[325] = "¡No soy su fan!"  -- {INES, dialogues/ending.moon}
t[614] = "¡No soy gruñona!"  -- {LEE, dialogues/ending.moon}
t[615] = "¡ES LA BANDA!"  -- {COLLECTOR, dialogues/ending.moon}
t[326] = "Qué he hecho."  -- {INES, dialogues/ending.moon}
t[616] = "¿QUIÉN QUIERE IR AL LAGO FENFEF?"  -- {LEE, dialogues/ending.moon}
t[617] = "¡Yo! ¡Yo!"  -- {PEPPE, dialogues/ending.moon}
t[618] = "¿Lago qué?"  -- {ANDREA, dialogues/ending.moon}
t[619] = "¡Viaje por carretera! ¡Sí!"  -- {PAOLO, dialogues/ending.moon}
t[620] = "Yo voy donde sea que vayan ellos."  -- {COLLECTOR, dialogues/ending.moon}
t[327] = "¿No deberíamos intentar enviarlos a sus propias líneas de tiempo?"  -- {INES, dialogues/ending.moon}
t[621] = "Nah, lo solucionamos después."  -- {LEE, dialogues/ending.moon}
t[622] = "Tenemos tiempo de sobra."  -- {LEE, dialogues/ending.moon}
t[623] = "Entonces, ¿has aprendido algo bueno de esta experiencia?"  -- {LEE, dialogues/ending.moon}
t[328] = "Nunca te fíes en tus dispositivos."  -- {ECHO, dialogues/ending.moon}
t[624] = "Siempre dices lo mismo."  -- {LEE, dialogues/ending.moon}
t[329] = "Eres aún más raro en el futuro."  -- {ECHO, dialogues/ending.moon}
t[625] = "Eso espero, practico todos los días."  -- {LEE, dialogues/ending.moon}
t[330] = "Debería presentarme para Presidente."  -- {ECHO, dialogues/ending.moon}
t[626] = "«Presidenta Inés»."  -- {LEE, dialogues/ending.moon}
t[627] = "Eso suena bien."  -- {LEE, dialogues/ending.moon}
t[331] = "Nunca pagues $0 por un juego de aventura point & click en el que puedes donar."  -- {ECHO, dialogues/ending.moon}
t[628] = "Sabias palabras."  -- {LEE, dialogues/ending.moon}
t[629] = "¡BIEN, NIÑOS!"  -- {LEE, dialogues/ending.moon}
t[630] = "¡CANTEMOS ALGUNAS CANCIONES DE VIAJE!"  -- {LEE, dialogues/ending.moon}
t[631] = "¡Juguemos!"  -- {PAOLO, dialogues/ending.moon}
t[632] = "¡¡¡SÍ!!!"  -- {COLLECTOR, dialogues/ending.moon}
t[332] = "... este va a ser un viaje muuuy largo."  -- {INES, dialogues/ending.moon}
t[333] = "Volver al juego"  -- {TEXT, gui/options.moon}
t[335] = "Volumen"  -- {TEXT, gui/options.moon}
t[649] = "Pantalla completa"  -- {TEXT, gui/options.moon}
t[650] = "Saltar diálogos con clic izquierdo"  -- {TEXT, gui/options.moon}
t[651] = "Saltar diálogos con clic derecho"  -- {TEXT, gui/options.moon}
t[344] = "Comenzar"  -- {TEXT, gui/start.moon}
t[345] = "Opciones"  -- {TEXT, gui/start.moon}
t[652] = "<Español>"  -- {TEXT, gui/start.moon}
t[346] = "Creado, escrito y diseñado por"  -- {TEXT, credits.moon}
t[347] = "Programado por"  -- {TEXT, credits.moon}
t[348] = "Arte y animación por"  -- {TEXT, credits.moon}
t[349] = "Música original por"  -- {TEXT, credits.moon}
t[350] = "Arte adicional por"  -- {TEXT, credits.moon}
t[351] = "Efectos de sonido adicionales por"  -- {TEXT, credits.moon}
t[653] = "Fuente LanaPixel por"  -- {TEXT, credits.moon}
t[352] = "Hecho con"  -- {TEXT, credits.moon}
t[353] = "Motor de audio"  -- {TEXT, credits.moon}
t[354] = "Diseño GUI"  -- {TEXT, credits.moon}
t[356] = "¡Gracias por jugar!"  -- {TEXT, credits.moon}

return t
